version: '2.1'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.20.0.2:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: filipe.a
    depends_on:
      - db
    networks:
      - poker-network
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: filipe.a
    networks:
      - poker-network
networks:
  poker-network:
    driver: bridge
