name: Continuous Integration

on:
  push:
    branches: 
      - main 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      run: ./mvnw clean package

    - name: Docker Compose Build
      working-directory: ./poker-manager-api
      run: docker compose build

    - name: Push to Docker Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/poker-manager-api-app:latest ${{ secrets.DOCKER_USERNAME }}/poker-manager-api-app:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/poker-manager-api-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/poker-manager-api-app:latest
